<?php
const DB_HOST = 'localhost';
const DB_USER = '';
const DB_PASS = '';
const DB_NAME = 'project_jun1312';
const LOGO_IMAGE = '';
const FOOTER_TEXT = '';
const VIEWS_FOLDER = '..' . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'view' . DIRECTORY_SEPARATOR . '';
const TEMPLATES_FOLDER = VIEWS_FOLDER . DIRECTORY_SEPARATOR . 'templates' . DIRECTORY_SEPARATOR;
const PAGES_FOLDER = VIEWS_FOLDER . DIRECTORY_SEPARATOR . 'pages' . DIRECTORY_SEPARATOR;
const ADMIN_PAGES_FOLDER = VIEWS_FOLDER . DIRECTORY_SEPARATOR . 'admin' . DIRECTORY_SEPARATOR;
const SITE_NAME = 'PAGE CREATOR';



