<?php
const DB_HOST ='localhost';
const DB_USER ='root';
const DB_PASS ='';
const DB_NAME= 'project_jun1312';
const LOGO_IMAGE='';
const FOOTER_TEXT='';

const VIEWS_DIR = '..'.DIRECTORY_SEPARATOR.'app'.DIRECTORY_SEPARATOR.'view'.DIRECTORY_SEPARATOR.'';
const TEMPLATES_DIR=VIEWS_DIR. DIRECTORY_SEPARATOR.'templates'.DIRECTORY_SEPARATOR;
const TEMPLATES_FOLDER = VIEWS_DIR. DIRECTORY_SEPARATOR.'templates'.DIRECTORY_SEPARATOR;
const PAGES_DIR = VIEWS_DIR. DIRECTORY_SEPARATOR.'pages'.DIRECTORY_SEPARATOR;
const ADMIN_PAGES_DIR = VIEWS_DIR. DIRECTORY_SEPARATOR.'admin'.DIRECTORY_SEPARATOR;
const SITE_NAME = 'PAGE CREATOR';

